# Generated by Django 4.1 on 2022-08-05 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlsearchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, max_length=200, null=True)),
                ('URL', models.CharField(blank=True, max_length=200, null=True)),
                ('registered_date', models.DateField(default=datetime.date(2022, 8, 5))),
                ('proba', models.FloatField(default=0.0)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
