# Generated by Django 4.1 on 2022-08-06 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('urlsearchapp', '0002_searchlist_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchlist',
            name='registered_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
